spring.application.name=backend
aws.region=us-east-2
aws.dynamodb.incidentsTable=Incidents
aws.dynamodb.metricsTable=Metrics
aws.s3.bucketName=cloudops-insight--uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
aws.bedrock.modelId=global.amazon.nova-2-lite-v1:0
app.auth.username=admin
app.auth.password=password123
security.jwt.secret=cloudops-insight-super-secret-dev-key-12345678901234567890
security.jwt.expiration=86400000