spring.application.name=backend
aws.region=us-east-2
aws.dynamodb.incidentsTable=Incidents
aws.dynamodb.metricsTable=Metrics
aws.s3.bucketName=cloudops-insight--uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
aws.bedrock.modelId=global.amazon.nova-2-lite-v1:0